#pragma once

#define FASTFETCH_PROJECT_NAME "terminalfont-detect"
#define FASTFETCH_PROJECT_VERSION "0.1.0"
#define FASTFETCH_PROJECT_VERSION_MAJOR 0
#define FASTFETCH_PROJECT_VERSION_MINOR 1
#define FASTFETCH_PROJECT_VERSION_PATCH 0
#define FASTFETCH_PROJECT_VERSION_GIT ""
#define FASTFETCH_PROJECT_VERSION_TWEAK ""
#define FASTFETCH_PROJECT_VERSION_TWEAK_NUM 0
#define FASTFETCH_PROJECT_CMAKE_BUILD_TYPE "Release"
#define FASTFETCH_PROJECT_HOMEPAGE_URL ""
#define FASTFETCH_PROJECT_DESCRIPTION ""
#define FASTFETCH_PROJECT_LICENSE ""

#define FASTFETCH_TARGET_DIR_ROOT "/"
#define FASTFETCH_TARGET_DIR_USR "/usr"
#define FASTFETCH_TARGET_DIR_HOME "~"
#define FASTFETCH_TARGET_DIR_ETC "/etc"

#define FASTFETCH_TARGET_DIR_INSTALL_SYSCONF "/etc"
